# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


# 测试类
class TestBaidu():
    # 在用例执行之前的操作
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    # 在用例执行之后的操作
    def teardown_method(self, method):
        self.driver.quit()

    def test_baidu(self):
        # 打开一个网页
        self.driver.get("https://www.baidu.com/")
        # 设置窗口大小
        self.driver.set_window_size(1546, 922)
        # 定位一个元素并且 输入操作
        self.driver.find_element(By.ID, "kw").send_keys("霍格沃兹测试开发")
        # 定位一个元素并且点击
        self.driver.find_element(By.ID, "su").click()
        self.driver.find_element(By.ID, "su").click()
        element = self.driver.find_element(By.ID, "su")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()

